# Generated by Django 5.0.4 on 2024-04-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('disponible', models.BooleanField()),
                ('tipo', models.CharField(choices=[('AUD', 'Auditorio'), ('CON', 'Sala de Conferencias'), ('AUL', 'Aula'), ('LAB', 'Laboratorio')], default='AUL', max_length=3)),
            ],
        ),
    ]
